{% set name = "parallel-hashmap" %}
{% set version = "1.37" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://github.com/greg7mdp/parallel-hashmap/archive/{{ version }}.tar.gz
  sha256: 2ac652be0552fcb53a1163c08c1f28f29f0756594fcc587eebb4d8b363153709

build:
  number: 0
  noarch: true

requirements:
  build:
    - {{ compiler('c') }}
    - {{ compiler('cxx') }}
    - cmake >=3.15

test:
  commands:
    - test -d ${PREFIX}/include/parallel_hashmap   # [unix]
    - test -f ${PREFIX}/include/parallel_hashmap/phmap.h   # [unix]
    - test -f ${PREFIX}/include/parallel_hashmap/meminfo.h   # [unix]
    - test -f ${PREFIX}/include/parallel_hashmap/btree.h   # [unix]

    - if exist %PREFIX%\\Library\\include\\parallel_hashmap (exit 0) else (exit 1)   # [win]
    - if exist %PREFIX%\\Library\\include\\parallel_hashmap\\phmap.h (exit 0) else (exit 1)   # [win]
    - if exist %PREFIX%\\Library\\include\\parallel_hashmap\\meminfo.h (exit 0) else (exit 1)   # [win]
    - if exist %PREFIX%\\Library\\include\\parallel_hashmap\\btree.h (exit 0) else (exit 1)   # [win]

about:
  home: https://github.com/greg7mdp/parallel-hashmap
  license: Apache-2.0
  license_family: APACHE
  license_file: LICENSE
  summary: A family of header-only, very fast and memory-friendly hashmap and btree containers.

extra:
  recipe-maintainers:
    - hadim
