context:
  name: parallel-hashmap
  version: 2.0.0

package:
  name: ${{ name|lower }}
  version: ${{ version }}

source:
  url: https://github.com/greg7mdp/parallel-hashmap/archive/v${{ version }}.tar.gz
  sha256: 4f462f51a3468166ea4cf87c80e001dc1999093264cf55cbda3492ca39a7730b

build:
  number: 0
  noarch: generic
  script: |
    cmake -DCMAKE_INSTALL_PREFIX=$PREFIX \
          -DCMAKE_PREFIX_PATH=$PREFIX \
          -DPHMAP_BUILD_TESTS=OFF \
          -DPHMAP_BUILD_EXAMPLES=OFF \
          -GNinja \
          -B build
    cmake --build build --config Release
    cmake --install build

requirements:
  build:
    - ${{ compiler('c') }}
    - ${{ compiler('cxx') }}
    - ${{ stdlib("c") }}
    - cmake >=3.15
    - ninja

tests:
  - package_contents:
      include:
        - parallel_hashmap/btree.h
        - parallel_hashmap/meminfo.h
        - parallel_hashmap/phmap.h
        - parallel_hashmap/phmap_base.h
        - parallel_hashmap/phmap_bits.h
        - parallel_hashmap/phmap_config.h
        - parallel_hashmap/phmap_dump.h
        - parallel_hashmap/phmap_fwd_decl.h
        - parallel_hashmap/phmap_utils.h

about:
  license: Apache-2.0
  license_file: LICENSE
  summary: A family of header-only, very fast and memory-friendly hashmap and btree containers.
  homepage: https://github.com/greg7mdp/parallel-hashmap

extra:
  recipe-maintainers:
    - hadim
